name: 'AWS SSM Remote Port Forwarding'
description: 'Forward a remote port to a local port using AWS SSM'
author: 'Enkhjil Enkhbaatar <enkhjil.eb@gmail.com>'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  target:
    description: 'The target instance ID'
    required: true
  host:
    description: 'The remote host to forward the port from'
    required: true
  port:
    description: 'The remote port to forward'
    required: true
  local-port:
    description: 'The local port to forward to'
    required: true

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
